### ISSUE TITLE
Feedback Sprint 2

### ISSUE THREAD

**Issue by MarciaMillanao** [VioletaLibertad/scl-2018-05-bc-core-am-datadashboard#11]
Hola Chicas
Estuve revisando el avance que llevan y tengo algunos comentarios:

1.- Les recomiendo usar nombre de identificadores (variables en js, clases o id en html & css) bien descriptivos y en inglés.

2.- Utilicen todo el HTML semántico (vi que usaron section), con eso me refiero a las etiquetas `<header></header> <section></section> <article></article> <aside></aside> <nav></nav> <footer></footer>`

3.- Utilicen milestones para ver el avance de los issues, esto es como un trello pero en github (similar) , les dejo dos vídeos de guía https://www.youtube.com/watch?v=9SZSHGA95x4
https://www.youtube.com/watch?v=nI5VdsVl0FM

Vamos con todo.

**Comment by Boutaudn** [comment]
Gracias Marcia! ya empezamos a usar milestones
