### ISSUE TITLE
Secciones en HTML listo

### ISSUE THREAD

**Issue by VioletaLibertad** [VioletaLibertad/scl-2018-05-bc-core-am-datadashboard#2]
Le agregué varias secciones al HTML, para que las revises :)

**Comment by Boutaudn** [comment]
Estuve buscando cómo hacer la función del search y encontré varios métodos como match(), find(), exec() o el mismo filter que pasamos en clase que podrían servir, pero con el formato de json no sé como aplicarlos o cuál sería efectivo.
Cualquier dato que sepas sobre este tema me cuentas 💮

**Comment by VioletaLibertad** [comment]
Genial, lo unimos con la clase de hoy y todo será maravilloso :)
