### ISSUE TITLE
MVP?

### ISSUE THREAD

**Issue by VioletaLibertad** [VioletaLibertad/scl-2018-05-bc-core-am-datadashboard#5]
Estaba pensando, que quizá el Minimo Producto Viable que deberiamos presentar, sería el que al seleccionar desde el dashboard 'Lima' -> y se muestren los cohorts, y puedas entrar a uno y todo eso. Y el botón de búsqueda. Onda, dejar la parte de Sao Paulo, México y Santiago sin activarse xq igual no tenemos esos datos como para agregarlos. Que opinas?

**Comment by Boutaudn** [comment]
Creo que estamos cerca 😃 te mandé un archivo por slack.
Pero me urge que aún no sabemos aplicar la búsqueda.

**Comment by VioletaLibertad** [comment]
Revisé lo que me mandaste por slack y está buenísimo. Mañana voy a trabajar en usar eso que mandaste y unirlo con la estreuctura base que tenemos que tener. Lo vamos a lograr!!! 😄
